services:
  casejoin-client:
    image: casejoin-client
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 4242:4200
    networks:
      casejoin-net:

networks:
  casejoin-net:
