services:
  casejoin-api:
    build:
      context: ./casejoin-api
      dockerfile: Dockerfile
    ports:
      - '8081:8080'
    environment:
      - SPRING_DATASOURCE_url=jdbc:postgresql://casejoin-postgres:5432/casejoindb
      - SPRING_DATASOURCE_USERNAME=admin
      - SPRING_DATASOURCE_PASSWORD=keypass
    depends_on:
      - casejoin-postgres
    networks:
      casejoin-net:
    restart: on-failure

  casejoin-client:
    image: casejoin-client
    build:
      context: ./casejoin-client
      dockerfile: Dockerfile
    ports:
      - 4242:4200
    networks:
      casejoin-net:

  casejoin-postgres:
    image: 'postgres:latest'
    container_name: casejoin-postgres
    environment:
      - POSTGRES_DB=casejoindb
      - POSTGRES_PASSWORD=keypass
      - POSTGRES_USER=admin
    ports:
      - 5433:5432
    volumes:
      - ./postgres-db:/var/lib/postgresql/data
    networks:
      casejoin-net:

volumes:
  postgres-db:
networks:
  casejoin-net: